#!/bin/sh

has_error=false

for rule in "${rules[@]}"; do
	command="${rule%%:*}"
	message="${rule##*:}"

	eval "$command"

	if [ $? -eq 0 ]; then
		printf "\e[1m${command}...\e[0m \e[32mOK\e[0m\n"
	else
		printf "\e[1m${command}...\e[0m \e[31mFAIL: ${message}\e[0m\n"
		has_error=true
	fi
done

$has_error && exit 1
