#!/bin/sh

for rule in "${rules[@]}"; do
	eval "$rule"

	if [ $? -eq 0 ]; then
		printf "\e[1m${rule}...\e[0m \e[32mOK\e[0m\n"
	else
		printf "\e[1m${rule}...\e[0m \e[31mFAIL\e[0m\n"
		exit 1
	fi
done

echo "Successfully passed all rules!"
